# SPDX-FileCopyrightText: Copyright (c) 2022 Anton Shatokhin
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".clang-format",
    ".gitattributes",
    ".gitignore",
    "**.json",
    "**.md",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.pdd",
    "**/*.csv",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "**/Gemfile.lock",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2022 Anton Shatokhin"
SPDX-License-Identifier = "MIT"
